### ISSUE TITLE
Decentraland hackathon prize

### ISSUE THREAD

**Issue by nearnshaw** [mass9/Shivalay#1]
Hi Pranav and Prashant

I'm Nico Earnshaw, I work at Decentraland as product owner of the SDK. Sorry I'm reaching out like this but I ddin't find any other way to reach out to you.

I wanted to let you know that your scene has won the 20th place in the Game Jam!  Congratulations!!

https://decentraland.org/blog/announcements/game-jam-2019-the-results-are-in/

To receive your prize of 25,000 MANA, you must have an Ethereum wallet to hold these tokens. If you don't already have one, we recommend either Metamask or Dapper. But any other Ethereum wallet should also work.

Please send me an email to nearnshaw@decentraland.org with your public key address, and we'll send you your prize shortly!

Cheers
Nico

**Comment by nearnshaw** [comment]
I forgot to mention the prize also includes 1 parcel of LAND in Decentraland, where you're free to deploy any content you want to share with others! :)

**Comment by prashantktiwari** [comment]
Email sent :)
